from django.db import models
from django.utils import timezone


class DiscoverItem(models.Model):
    """A single card in the swipe deck — a not-yet-decided recommendation."""

    class MediaType(models.TextChoices):
        MOVIE = 'movie', 'Movie'
        TV = 'tv', 'TV Show'

    class Source(models.TextChoices):
        RECOMMENDATION = 'recommendation', 'Because You Like'
        ANTICIPATED = 'anticipated', 'New & Anticipated'

    tmdb_id = models.IntegerField()
    media_type = models.CharField(max_length=10, choices=MediaType.choices)
    title = models.CharField(max_length=500)
    overview = models.TextField(blank=True)
    poster_path = models.CharField(max_length=500, blank=True)
    backdrop_path = models.CharField(max_length=500, blank=True)
    release_date = models.DateField(null=True, blank=True)
    vote_average = models.FloatField(default=0)
    genres = models.CharField(max_length=500, blank=True)
    source = models.CharField(max_length=20, choices=Source.choices)
    source_title = models.CharField(max_length=500, blank=True)
    added_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('tmdb_id', 'media_type')
        ordering = ['-added_at']

    def __str__(self):
        return f'{self.title} ({self.media_type})'

    @property
    def poster_url(self):
        if self.poster_path:
            return f'https://image.tmdb.org/t/p/w500{self.poster_path}'
        return None

    @property
    def backdrop_url(self):
        if self.backdrop_path:
            return f'https://image.tmdb.org/t/p/w1280{self.backdrop_path}'
        return None

    @property
    def is_released(self):
        return bool(self.release_date and self.release_date <= timezone.now().date())


class DiscoverDecision(models.Model):
    """
    Permanent swipe record. Kept forever (even after the DiscoverItem is
    deleted) so a title the user has already swiped on — either direction —
    is never regenerated by the nightly tasks and never reshown.
    """

    class Direction(models.TextChoices):
        LEFT = 'left', 'Not Interested'
        RIGHT = 'right', 'Interested'

    tmdb_id = models.IntegerField()
    media_type = models.CharField(max_length=10)
    direction = models.CharField(max_length=10, choices=Direction.choices)
    decided_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('tmdb_id', 'media_type')

    def __str__(self):
        return f'{self.media_type}:{self.tmdb_id} — {self.direction}'
