# Generated by Django 4.2.30 on 2026-08-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('download_complete', 'Download Completed'), ('file_moved', 'File Moved'), ('file_failed', 'File Move Failed'), ('episodes_queued', 'Episode(s) Queued'), ('movie_available', 'Movie Available'), ('download_failed', 'Search Failed'), ('storage_warning', 'Storage Warning')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
