# Generated by Django 4.2.30 on 2026-06-13 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('digital_release_date', models.DateField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('genres', models.CharField(blank=True, max_length=500)),
                ('vote_average', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('released', 'Released'), ('upcoming', 'Upcoming'), ('in_production', 'In Production')], default='released', max_length=30)),
                ('download_status', models.CharField(choices=[('none', 'Not Queued'), ('waiting_release', 'Waiting for Digital Release'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded')], default='none', max_length=20)),
                ('is_favourite', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('returning', 'Returning Series'), ('ended', 'Ended'), ('cancelled', 'Cancelled'), ('in_production', 'In Production'), ('planned', 'Planned')], default='returning', max_length=50)),
                ('number_of_seasons', models.IntegerField(default=0)),
                ('number_of_episodes', models.IntegerField(default=0)),
                ('networks', models.CharField(blank=True, max_length=500)),
                ('genres', models.CharField(blank=True, max_length=500)),
                ('vote_average', models.FloatField(default=0)),
                ('is_favourite', models.BooleanField(default=False)),
                ('monitor_new_episodes', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('season_number', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('episode_count', models.IntegerField(default=0)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='media_tracker.tvshow')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('show', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('still_path', models.CharField(blank=True, max_length=500)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(default=0)),
                ('download_status', models.CharField(choices=[('none', 'Not Queued'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('missing', 'Missing')], default='none', max_length=20)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='media_tracker.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
