# Generated by Django 4.2.30 on 2026-06-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='monitor_from',
            field=models.DateField(blank=True, help_text='Only auto-queue episodes that air on or after this date. Advances as new episodes are queued.', null=True),
        ),
    ]
