# Generated by Django 4.2.30 on 2026-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_tracker', '0003_episode_air_datetime_tvshow_tvmaze_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='download_status',
            field=models.CharField(choices=[('none', 'Not Queued'), ('awaiting_release', 'Awaiting Release'), ('waiting_for_download', 'Waiting for Download'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('missing', 'Missing')], default='none', max_length=20),
        ),
    ]
