# Generated by Django 4.2.30 on 2026-09-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('vote_average', models.FloatField(default=0)),
                ('genres', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('recommendation', 'Because You Like'), ('anticipated', 'New & Anticipated')], max_length=20)),
                ('source_title', models.CharField(blank=True, max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
        migrations.CreateModel(
            name='DiscoverDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('media_type', models.CharField(max_length=10)),
                ('direction', models.CharField(choices=[('left', 'Not Interested'), ('right', 'Interested')], max_length=10)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('tmdb_id', 'media_type')},
            },
        ),
    ]
