# Generated by Django 4.2.30 on 2026-06-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('episode', 'TV Episode'), ('movie', 'Movie')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching'), ('found', 'Found'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('waiting_release', 'Waiting for Release')], default='pending', max_length=20)),
                ('episode_id', models.IntegerField(blank=True, null=True)),
                ('movie_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('torrent_hash', models.CharField(blank=True, max_length=100)),
                ('torrent_name', models.CharField(blank=True, max_length=500)),
                ('magnet_link', models.TextField(blank=True)),
                ('progress', models.FloatField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('download_speed', models.BigIntegerField(default=0)),
                ('eta_seconds', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
