# Generated by Django 4.2.30 on 2026-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaditem',
            name='quality',
            field=models.CharField(default='1080p', max_length=10),
        ),
    ]
