# Generated by Django 4.2.30 on 2026-06-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_add_quality_to_downloaditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaditem',
            name='result_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='search_query',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
