# Generated by Django 4.2.30 on 2026-06-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_add_search_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_path', models.CharField(max_length=2000)),
                ('dest_path', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('moving', 'Moving'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('download_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_moves', to='downloads.downloaditem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
