# Generated by Django 4.2.30 on 2026-07-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0006_downloaditem_search_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemove',
            name='bytes_moved',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filemove',
            name='bytes_total',
            field=models.BigIntegerField(default=0),
        ),
    ]
