# Generated by Django 4.2.30 on 2026-08-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0007_filemove_bytes_moved_filemove_bytes_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloaditem',
            name='season_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downloaditem',
            name='media_type',
            field=models.CharField(choices=[('episode', 'TV Episode'), ('season', 'TV Season'), ('movie', 'Movie')], max_length=10),
        ),
    ]
