# Generated by Django 4.2.30 on 2026-06-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True)),
                ('download_path', models.CharField(blank=True, help_text='Where qBittorrent saves files while downloading. Sent as save_path when adding a torrent.', max_length=1000)),
                ('completed_path', models.CharField(blank=True, help_text='Where Daredevil moves files after the download finishes.', max_length=1000)),
            ],
            options={
                'verbose_name': 'Category Path',
                'ordering': ['category_name'],
            },
        ),
    ]
