# Generated by Django 4.2.30 on 2026-06-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbt', '0003_extratab'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypath',
            name='qbt_save_path',
            field=models.CharField(blank=True, help_text="Save path sent to qBittorrent when adding torrents (qBittorrent's container path, e.g. /downloads).", max_length=1000),
        ),
        migrations.AlterField(
            model_name='categorypath',
            name='download_path',
            field=models.CharField(blank=True, help_text="Where Daredevil looks for downloaded files (Daredevil's container path, e.g. /media/downloads).", max_length=1000),
        ),
    ]
