# Generated by Django 4.2.30 on 2026-06-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlexIgnored',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('ignored_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ignored_at'],
            },
        ),
    ]
