# Generated by Django 4.2.30 on 2026-06-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_category_prefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('episodes_queued', 'New Episodes Queued'), ('movie_available', 'Movie Available Digitally'), ('download_complete', 'Download Complete'), ('download_failed', 'Download / Search Failed'), ('file_moved', 'File Moved to Library'), ('file_failed', 'File Move Failed'), ('storage_warning', 'Storage Warning'), ('', 'Uncategorised')], default='', max_length=50),
        ),
    ]
